apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: database-service-ecosystem-internal
  name: database-service-ecosystem-internal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database-service-ecosystem-internal
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: database-service-ecosystem-internal
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: development
          image: postgres:9.6-alpine
          name: database.service.ecosystem.internal
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
status: {}
